server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/catalogue_db
    username: admin
    password: admin
  flyway:
    schemas:
      - public
      - catalogue
  jpa:
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/manager-crud
logging:
  level:
    sql: info
